plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.accelledsinertial'
    compileSdk 35

    defaultConfig {
        applicationId 'com.example.accelledsinertial.continuous.gpsspeed.v30.decimals4'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '3.0-velocimetro-gps-4-decimales'
    }
}

