plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.accelledsinertial'
    compileSdk 35

    defaultConfig {
        applicationId 'com.example.accelledsinertial.gpsonly.v45.permanentlogmarks'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '4.5-gps-marcas-log-permanentes'
    }
}
