plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.accelledsinertial'
    compileSdk 35

    defaultConfig {
        applicationId 'com.example.accelledsinertial.gpsonly.v48.sharedleftright'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '4.8-gps-rango-comun-izquierda-derecha'
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
